name: Lint Markdown Files

on:
  pull_request:
    paths:
      - "**.md"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install proselint
        run: |
          python -m pip install --upgrade pip
          pip install proselint

      - name: Run proselint on Markdown files
        run: |
          find . -name "*.md" -print0 | xargs -0 -n1 proselint
